### ISSUE TITLE
Only 2 of XX episodes are shown

### ISSUE THREAD

**Issue by Liese2007** [Podcast-Republic/PRApp#190]
The following podcast from ARD Mediathek is not shown with all episodes.
Kalk & Welk - Die fabelhaften Boomer Boys
Podcast: https://www.podcastrepublic.net/podcast/1673046567

Original source:
https://www.ardaudiothek.de/sendung/kalk-und-welk/10777871/

Any obvious reason for this ?

Greets
Joerg

**Comment by gemiren** [comment]
This app is designed to retrieve episodes from a podcast RSS feed. A podcast RSS feed is a specially formatted file that contains information about a podcast and its episodes. When you subscribe to a podcast using an app or software, the app reads the RSS feed and displays the episodes for you to listen to.

In the case of this podcast, the RSS feed is located at https://www.radioeins.de/archiv/podcast/kalk_welk.xml/feed=podcast.xml. If you open the feed with any web browser app you can see there are only three episodes in the podcast. This podcast publisher has chosen to only include the most recent episodes in the RSS feed. 

If you're unfamiliar with how podcast RSS feeds work, here's a quick summary: When you subscribe to a podcast using an app or software, the app reads the RSS feed and checks for any new episodes. If there are new episodes, the app will download them and make them available for you to listen to. This is why it's important for podcast publishers to include all the relevant information about their podcast and its episodes in the RSS feed, so that users can easily find and access the content they're interested in.
