### ISSUE TITLE
Inconstant source for episode description

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#244]
Sometimes the app uses the episode descriptions that contains in the `<description>` tag but sometimes it displays the contents of the `<itunes:summary>` tag.

[This](https://www.merriam-webster.com/wotd/feed/rss2) feed uses HTML in the `<description>` tag
![Screenshot_2023-06-17-16-37-31-353_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/367b0126-fc3b-422a-9931-32e24595ab06)
and Markdown in the `<itunes:summary>` tag.
![Screenshot_2023-06-17-16-37-43-332_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/cef93116-660e-4193-96ec-845e1daa16d9)

**Comment by gemiren** [comment]
Ideally, the summary tag should only be used as the summary and the description tag should be used as the full description. However, some podcasts put the same content in both tags, some put the wrong tags. Therefore, in the app, it tries to figure out which content of those two tags are more likely to be the true full description by taking the longer content of those two tags. That's why you see the inconsistent behavior.
